# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f36d6358518745d92d1032da5a7e1f82cd7fdf2311a363a4042b107862d49bef853ee78db0653fc593cf3afe1d03ed085759f451ec976f9804897565f380e70

test:
  secret_key_base: b76f8cfad38ca3f7b1fd13e42480826522cf3a06a4fbc36cc6ab1d5021d3d0173aa6d77882145abae63a73230aac80de63f24efb1db328824c43ffa11f33ed18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
